# Write your MySQL query statement below
SELECT TMP.MACHINE_ID as machine_id, ROUND(SUM(TMP.TIME_DIFF)/COUNT(TMP.TIME_DIFF),3) AS processing_time FROM
(
    SELECT A.MACHINE_ID,

    ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'END' THEN A.TIMESTAMP ELSE 0 END ),3)
    -
    ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'START' THEN A.TIMESTAMP ELSE 0 END),3) AS 'TIME_DIFF'

    FROM ACTIVITY AS A
    GROUP BY A.MACHINE_ID, A.PROCESS_ID

) AS TMP
GROUP BY TMP.MACHINE_ID